inputSpec: 'https://orthanc.uclouvain.be/api/orthanc-openapi.json'

generatorName: rust
outputDir: orthanc_client_ogen

# https://openapi-generator.tech/docs/generators/rust/#config-options
additionalProperties:
  packageName: orthanc_client_ogen
  version: 1.12.8
  preferUnsignedInt: true
  supportAsync: true
  supportMiddleware: true
  topLevelApiClient: true
  library: reqwest
  # useBonBuilder: false
