services:
  dev:
    image: docker.io/jodogne/orthanc-plugins:1.12.8
    volumes:
      - dev:/var/lib/orthanc/db
      - ./orthanc_config/dev:/etc/orthanc:ro
      - ../target:/target:ro
    ports:
      - 4242:4242
      - 8042:8042
    environment:
      RUST_BACKTRACE: '1'
      RUST_LOG: 'info'

  pacs:
    image: docker.io/jodogne/orthanc-plugins:1.12.8
    ports:
      - 8043:8042
    volumes:
      - pacs:/var/lib/orthanc/db
      - ./orthanc_config/pacs:/etc/orthanc:ro

  peer:
    image: docker.io/jodogne/orthanc-plugins:1.12.8
    ports:
      - 8044:8042
    volumes:
      - peer:/var/lib/orthanc/db
      - ./orthanc_config/peer:/etc/orthanc:ro

volumes:
  dev:
  pacs:
  peer:
