services:
  dev:
    image: docker.io/jodogne/orthanc-plugins:1.12.8
    volumes:
      - storage:/var/lib/orthanc/db
      - ./Orthanc.jsonc:/etc/orthanc/orthanc.json:ro
      - ./output.txt:/tmp/output.txt:rw
      - ../target:/target:ro
    ports:
      - 4242:4242
      - 8042:8042
    environment:
      RUST_BACKTRACE: '1'

volumes:
  storage:
